"""empty message

Revision ID: abc
Revises: 8a43dca5bea2
Create Date: 2023-07-20 14:37:17.943068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc'
down_revision = "8a43dca5bea2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('planet_id', existing_type=sa.ForeignKey("planet.id"), nullable=True)
        batch_op.alter_column('character_id', existing_type=sa.ForeignKey("character.id"), nullable=True)
         
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
